const configured=window.SUPABASE_URL&&window.SUPABASE_ANON_KEY&&!window.SUPABASE_URL.includes('YOUR_')&&!window.SUPABASE_ANON_KEY.includes('YOUR_');
const loginBox=document.querySelector('#login'),app=document.querySelector('#app'),loginForm=document.querySelector('#loginForm'),loginMsg=document.querySelector('#loginMsg');
let client=null;
if(configured) client=window.supabase.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY);
function msg(el,text,ok=false){el.textContent=text;el.style.color=ok?'#18794e':'#b02b4e'}
function showApp(){loginBox.classList.add('hidden');app.classList.remove('hidden');loadProducts()}
async function check(){if(!client){msg(loginMsg,'Chưa cấu hình Supabase. Xem file SETUP.md trong repo.');return}const {data}=await client.auth.getSession();if(data.session)showApp()}
loginForm.addEventListener('submit',async e=>{e.preventDefault();if(!client)return msg(loginMsg,'Chưa cấu hình Supabase.');msg(loginMsg,'Đang đăng nhập...',true);const {error}=await client.auth.signInWithPassword({email:email.value,password:password.value});if(error)msg(loginMsg,error.message);else showApp()});
logout.onclick=async()=>{if(client)await client.auth.signOut();app.classList.add('hidden');loginBox.classList.remove('hidden');};
const form=document.querySelector('#productForm');
async function loadProducts(){const box=document.querySelector('#productList');box.innerHTML='<p>Đang tải...</p>';if(!client)return;const {data,error}=await client.from('products').select('*').order('sort_order',{ascending:true}).order('created_at',{ascending:false});if(error){box.innerHTML='<p>Không tải được sản phẩm: '+error.message+'</p>';return}box.innerHTML=data.length?data.map(p=>`<article class="item"><img src="${esc(p.image_url)}" alt=""><div><h3>${esc(p.name)}</h3><p>${esc(p.category)} · ${p.active?'Đang hiển thị':'Đang ẩn'}${p.price?' · '+esc(p.price):''}</p></div><div class="actions"><button data-edit="${p.id}">Sửa</button><button class="danger" data-del="${p.id}">Xóa</button></div></article>`).join(''):'<p>Chưa có sản phẩm.</p>';box.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editProduct(data.find(p=>p.id===b.dataset.edit)));box.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>deleteProduct(b.dataset.del))}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function editProduct(p){productId.value=p.id;name.value=p.name;category.value=p.category;link.value=p.affiliate_url;image.value=p.image_url;description.value=p.description||'';price.value=p.price||'';sortOrder.value=p.sort_order||0;active.checked=p.active;formTitle.textContent='Chỉnh sửa sản phẩm';cancelEdit.classList.remove('hidden');scrollTo({top:0,behavior:'smooth'})}
cancelEdit.onclick=()=>{form.reset();productId.value='';formTitle.textContent='Thêm sản phẩm';cancelEdit.classList.add('hidden');active.checked=true;sortOrder.value=0}
form.addEventListener('submit',async e=>{e.preventDefault();if(!client)return;saveBtn.disabled=true;const payload={name:name.value.trim(),category:category.value,affiliate_url:link.value.trim(),image_url:image.value.trim(),description:description.value.trim(),price:price.value.trim(),sort_order:Number(sortOrder.value)||0,active:active.checked};let result;if(productId.value)result=await client.from('products').update(payload).eq('id',productId.value);else result=await client.from('products').insert(payload);saveBtn.disabled=false;if(result.error){msg(formMsg,result.error.message);return}msg(formMsg,'Đã lưu sản phẩm.',true);cancelEdit.click();loadProducts()});
async function deleteProduct(id){if(!confirm('Xóa sản phẩm này?'))return;const {error}=await client.from('products').delete().eq('id',id);if(error)alert(error.message);else loadProducts()}
refresh.onclick=loadProducts;check();