const configured=window.SUPABASE_URL&&window.SUPABASE_ANON_KEY&&!window.SUPABASE_URL.includes('YOUR_')&&!window.SUPABASE_ANON_KEY.includes('YOUR_');
const loginBox=document.querySelector('#login'),app=document.querySelector('#app'),loginForm=document.querySelector('#loginForm'),loginMsg=document.querySelector('#loginMsg');
let client=null;
if(configured) client=window.supabase.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY);
function msg(el,text,ok=false){el.textContent=text;el.style.color=ok?'#18794e':'#b02b4e'}
function showApp(){loginBox.classList.add('hidden');app.classList.remove('hidden');loadProducts()}
async function check(){if(!client){msg(loginMsg,'Chưa cấu hình Supabase. Hãy điền anon key trong supabase-config.js.');return}const {data}=await client.auth.getSession();if(data.session)showApp()}
loginForm.addEventListener('submit',async e=>{e.preventDefault();if(!client)return msg(loginMsg,'Chưa cấu hình Supabase.');msg(loginMsg,'Đang đăng nhập...',true);const {error}=await client.auth.signInWithPassword({email:document.querySelector('#email').value,password:document.querySelector('#password').value});if(error)msg(loginMsg,error.message);else showApp()});
document.querySelector('#logout').onclick=async()=>{if(client)await client.auth.signOut();app.classList.add('hidden');loginBox.classList.remove('hidden')};
const form=document.querySelector('#productForm');
const imageFile=document.querySelector('#imageFile');
const imagePreview=document.querySelector('#imagePreview');
imageFile.addEventListener('change',()=>{const file=imageFile.files[0];if(!file){imagePreview.innerHTML='';return}if(file.size>5*1024*1024){imageFile.value='';imagePreview.innerHTML='<small>Ảnh vượt quá 5MB.</small>';return}const url=URL.createObjectURL(file);imagePreview.innerHTML=`<img src="${url}" alt="Xem trước ảnh">`});
async function uploadImage(file){const ext=(file.name.split('.').pop()||'jpg').toLowerCase();const path=`${crypto.randomUUID()}.${ext}`;const {error}=await client.storage.from('product-images').upload(path,file,{cacheControl:'3600',upsert:false,contentType:file.type});if(error)throw error;const {data}=client.storage.from('product-images').getPublicUrl(path);return data.publicUrl}
async function loadProducts(){const box=document.querySelector('#productList');box.innerHTML='<p>Đang tải...</p>';if(!client)return;const {data,error}=await client.from('products').select('*').order('sort_order',{ascending:true}).order('created_at',{ascending:false});if(error){box.innerHTML='<p>Không tải được sản phẩm: '+esc(error.message)+'</p>';return}box.innerHTML=data.length?data.map(p=>`<article class="item"><img src="${esc(p.image_url||'')}" alt=""><div><h3>${esc(p.name)}</h3><p>${esc(p.category)} · ${p.active?'Đang hiển thị':'Đang ẩn'}${p.price?' · '+esc(p.price):''}</p></div><div class="actions"><button data-edit="${p.id}">Sửa</button><button class="danger" data-del="${p.id}">Xóa</button></div></article>`).join(''):'<p>Chưa có sản phẩm.</p>';box.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editProduct(data.find(p=>p.id===b.dataset.edit)));box.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>deleteProduct(b.dataset.del))}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function editProduct(p){document.querySelector('#productId').value=p.id;document.querySelector('#name').value=p.name;document.querySelector('#category').value=p.category;document.querySelector('#link').value=p.affiliate_url;document.querySelector('#image').value=p.image_url||'';document.querySelector('#description').value=p.description||'';document.querySelector('#price').value=p.price||'';document.querySelector('#sortOrder').value=p.sort_order||0;document.querySelector('#active').checked=p.active;document.querySelector('#formTitle').textContent='Chỉnh sửa sản phẩm';document.querySelector('#cancelEdit').classList.remove('hidden');imagePreview.innerHTML=p.image_url?`<img src="${esc(p.image_url)}" alt="Ảnh hiện tại">`:'';window.scrollTo({top:0,behavior:'smooth'})}
document.querySelector('#cancelEdit').onclick=()=>{form.reset();document.querySelector('#productId').value='';document.querySelector('#formTitle').textContent='Thêm sản phẩm';document.querySelector('#cancelEdit').classList.add('hidden');document.querySelector('#active').checked=true;document.querySelector('#sortOrder').value=0;imagePreview.innerHTML=''};
form.addEventListener('submit',async e=>{e.preventDefault();if(!client)return;const saveBtn=document.querySelector('#saveBtn');saveBtn.disabled=true;try{let imageUrl=document.querySelector('#image').value.trim();const file=imageFile.files[0];if(file){msg(document.querySelector('#formMsg'),'Đang tải ảnh...',true);imageUrl=await uploadImage(file)}const payload={name:document.querySelector('#name').value.trim(),category:document.querySelector('#category').value,affiliate_url:document.querySelector('#link').value.trim(),image_url:imageUrl,description:document.querySelector('#description').value.trim(),price:document.querySelector('#price').value.trim(),sort_order:Number(document.querySelector('#sortOrder').value)||0,active:document.querySelector('#active').checked};let result=document.querySelector('#productId').value?await client.from('products').update(payload).eq('id',document.querySelector('#productId').value):await client.from('products').insert(payload);if(result.error)throw result.error;msg(document.querySelector('#formMsg'),'Đã lưu sản phẩm.',true);document.querySelector('#cancelEdit').click();loadProducts()}catch(error){msg(document.querySelector('#formMsg'),error.message)}finally{saveBtn.disabled=false}});
async function deleteProduct(id){if(!confirm('Xóa sản phẩm này?'))return;const {error}=await client.from('products').delete().eq('id',id);if(error)alert(error.message);else loadProducts()}
document.querySelector('#refresh').onclick=loadProducts;
check();