const configured=window.SUPABASE_URL&&window.SUPABASE_ANON_KEY&&!window.SUPABASE_URL.includes('YOUR_')&&!window.SUPABASE_ANON_KEY.includes('YOUR_');
const loginBox=document.querySelector('#login'),app=document.querySelector('#app'),loginForm=document.querySelector('#loginForm'),loginMsg=document.querySelector('#loginMsg');
let client=null,productsCache=[];
if(configured) client=window.supabase.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY);
function msg(el,text,ok=false){el.textContent=text;el.style.color=ok?'#18794e':'#b02b4e'}
function formatPrice(v=''){const n=String(v).replace(/[^0-9]/g,'');return n?Number(n).toLocaleString('vi-VN')+'đ':''}
function showApp(){loginBox.classList.add('hidden');app.classList.remove('hidden');loadProducts()}
async function check(){if(!client){msg(loginMsg,'Chưa cấu hình Supabase.');return}const {data}=await client.auth.getSession();if(data.session)showApp()}
loginForm.addEventListener('submit',async e=>{e.preventDefault();if(!client)return msg(loginMsg,'Chưa cấu hình Supabase.');msg(loginMsg,'Đang đăng nhập...',true);const {error}=await client.auth.signInWithPassword({email:document.querySelector('#email').value,password:document.querySelector('#password').value});if(error)msg(loginMsg,error.message);else showApp()});
document.querySelector('#logout').onclick=async()=>{if(client)await client.auth.signOut();app.classList.add('hidden');loginBox.classList.remove('hidden')};
const form=document.querySelector('#productForm'),imageFile=document.querySelector('#imageFile'),imagePreview=document.querySelector('#imagePreview'),videoUrl=document.querySelector('#videoUrl'),videoPreview=document.querySelector('#videoPreview'),videoThumbnail=document.querySelector('#videoThumbnail');
imageFile.addEventListener('change',()=>{const file=imageFile.files[0];if(!file){imagePreview.innerHTML='';return}if(file.size>5*1024*1024){imageFile.value='';imagePreview.innerHTML='<small>Ảnh vượt quá 5MB.</small>';return}imagePreview.innerHTML=`<img src="${URL.createObjectURL(file)}" alt="Xem trước ảnh">`});
function isTikTokUrl(url){try{const u=new URL(url);const host=u.hostname.toLowerCase();return host==='tiktok.com'||host.endsWith('.tiktok.com')}catch{return false}}
let thumbnailTimer;
async function fetchTikTokThumbnail(url){videoPreview.innerHTML='<div class="video-loading">⏳ Đang lấy thumbnail TikTok...</div>';if(!url){videoThumbnail.value='';videoPreview.innerHTML='';return}if(!isTikTokUrl(url)){videoThumbnail.value='';videoPreview.innerHTML='<small>Vui lòng nhập link video TikTok hợp lệ.</small>';return}try{const {data,error}=await client.functions.invoke('tiktok-oembed',{body:{url}});if(error)throw new Error(error.message||'Không gọi được dịch vụ thumbnail.');if(!data?.thumbnail_url)throw new Error(data?.error||'TikTok không trả về thumbnail.');videoThumbnail.value=data.thumbnail_url;videoPreview.innerHTML=`<img src="${esc(data.thumbnail_url)}" alt="Thumbnail TikTok"><div class="video-meta"><b>${esc(data.title||'Video TikTok')}</b><small>Thumbnail lấy từ TikTok</small></div>`}catch(error){videoPreview.innerHTML=`<small>Không lấy được thumbnail tự động. Hãy kiểm tra Edge Function “tiktok-oembed” đã được deploy. (${esc(error.message)})</small>`}}
videoUrl.addEventListener('input',()=>{clearTimeout(thumbnailTimer);const url=videoUrl.value.trim();thumbnailTimer=setTimeout(()=>fetchTikTokThumbnail(url),500)});
videoUrl.addEventListener('blur',()=>fetchTikTokThumbnail(videoUrl.value.trim()));
async function uploadImage(file){const ext=(file.name.split('.').pop()||'jpg').toLowerCase();const path=`${crypto.randomUUID()}.${ext}`;const {error}=await client.storage.from('product-images').upload(path,file,{cacheControl:'3600',upsert:false,contentType:file.type});if(error)throw error;return client.storage.from('product-images').getPublicUrl(path).data.publicUrl}
function renderCategoryList(){const cats=[...new Set(productsCache.map(p=>p.category).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'vi'));document.querySelector('#categoryList').innerHTML=cats.map(c=>`<option value="${esc(c)}">`).join('')}
async function loadProducts(){const box=document.querySelector('#productList');box.innerHTML='<p>Đang tải...</p>';if(!client)return;const {data,error}=await client.from('products').select('*').order('pinned',{ascending:false}).order('sort_order',{ascending:true}).order('created_at',{ascending:false});if(error){box.innerHTML='<p>Không tải được sản phẩm: '+esc(error.message)+'</p>';return}productsCache=data||[];renderCategoryList();box.innerHTML=productsCache.length?productsCache.map(p=>`<article class="item" draggable="true" data-id="${p.id}"><span class="drag">☷</span><img src="${esc(p.image_url||'')}" alt=""><div><h3>${esc(p.name)} ${p.pinned?'📌':''}</h3><p>${esc(p.category)} · ${p.active?'Đang hiển thị':'Đang ẩn'}${p.price?' · '+esc(formatPrice(p.price)):''}${p.video_url?' · 🎬 Có video':''}</p></div><div class="actions"><button data-edit="${p.id}">Sửa</button><button class="danger" data-del="${p.id}">Xóa</button></div></article>`).join(''):'<p>Chưa có sản phẩm.</p>';box.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>editProduct(productsCache.find(p=>p.id===b.dataset.edit)));box.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>deleteProduct(b.dataset.del));enableDrag(box)}
function enableDrag(box){let dragged=null;box.querySelectorAll('.item').forEach(item=>{item.addEventListener('dragstart',()=>{dragged=item;item.classList.add('dragging')});item.addEventListener('dragend',async()=>{item.classList.remove('dragging');if(!dragged)return;const ids=[...box.querySelectorAll('.item')].map(x=>x.dataset.id);for(let i=0;i<ids.length;i++)await client.from('products').update({sort_order:i}).eq('id',ids[i]);loadProducts()});item.addEventListener('dragover',e=>{e.preventDefault();if(dragged&&dragged!==item){const r=item.getBoundingClientRect();if(e.clientY<r.top+r.height/2)item.before(dragged);else item.after(dragged)}})})}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function editProduct(p){document.querySelector('#productId').value=p.id;document.querySelector('#name').value=p.name;document.querySelector('#category').value=p.category;document.querySelector('#link').value=p.affiliate_url;videoUrl.value=p.video_url||'';videoThumbnail.value=p.video_thumbnail_url||'';document.querySelector('#image').value=p.image_url||'';document.querySelector('#description').value=p.description||'';document.querySelector('#price').value=p.price||'';document.querySelector('#sortOrder').value=p.sort_order||0;document.querySelector('#pinned').checked=!!p.pinned;document.querySelector('#active').checked=p.active;document.querySelector('#formTitle').textContent='Chỉnh sửa sản phẩm';document.querySelector('#cancelEdit').classList.remove('hidden');imagePreview.innerHTML=p.image_url?`<img src="${esc(p.image_url)}" alt="Ảnh hiện tại">`:'';videoPreview.innerHTML=p.video_thumbnail_url?`<img src="${esc(p.video_thumbnail_url)}" alt="Thumbnail TikTok hiện tại"><div class="video-meta"><small>Thumbnail TikTok đã lưu</small></div>`:'';window.scrollTo({top:0,behavior:'smooth'})}
document.querySelector('#cancelEdit').onclick=()=>{form.reset();document.querySelector('#productId').value='';document.querySelector('#formTitle').textContent='Thêm sản phẩm';document.querySelector('#cancelEdit').classList.add('hidden');document.querySelector('#active').checked=true;document.querySelector('#sortOrder').value=0;imagePreview.innerHTML='';videoPreview.innerHTML='';videoThumbnail.value=''};
form.addEventListener('submit',async e=>{e.preventDefault();if(!client)return;const saveBtn=document.querySelector('#saveBtn');saveBtn.disabled=true;try{let imageUrl=document.querySelector('#image').value.trim();const file=imageFile.files[0];if(file){msg(document.querySelector('#formMsg'),'Đang tải ảnh...',true);imageUrl=await uploadImage(file)}const payload={name:document.querySelector('#name').value.trim(),category:document.querySelector('#category').value.trim(),affiliate_url:document.querySelector('#link').value.trim(),video_url:videoUrl.value.trim(),video_thumbnail_url:videoThumbnail.value.trim(),image_url:imageUrl,description:document.querySelector('#description').value.trim(),price:formatPrice(document.querySelector('#price').value),sort_order:Number(document.querySelector('#sortOrder').value)||0,pinned:document.querySelector('#pinned').checked,active:document.querySelector('#active').checked};let result=document.querySelector('#productId').value?await client.from('products').update(payload).eq('id',document.querySelector('#productId').value):await client.from('products').insert(payload);if(result.error)throw result.error;msg(document.querySelector('#formMsg'),'Đã lưu sản phẩm.',true);document.querySelector('#cancelEdit').click();loadProducts()}catch(error){msg(document.querySelector('#formMsg'),error.message)}finally{saveBtn.disabled=false}});
async function deleteProduct(id){if(!confirm('Xóa sản phẩm này?'))return;const {error}=await client.from('products').delete().eq('id',id);if(error)alert(error.message);else loadProducts()}
document.querySelector('#refresh').onclick=loadProducts;
check();